/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTenantIdRouteRouteImport } from './routes/t/$tenantId/route'
import { Route as TTenantIdIndexRouteImport } from './routes/t/$tenantId/index'

const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantIdRouteRoute = TTenantIdRouteRouteImport.update({
  id: '/t/$tenantId',
  path: '/t/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantIdIndexRoute = TTenantIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTenantIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tenants': typeof TenantsRoute
  '/t/$tenantId': typeof TTenantIdRouteRouteWithChildren
  '/t/$tenantId/': typeof TTenantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tenants': typeof TenantsRoute
  '/t/$tenantId': typeof TTenantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tenants': typeof TenantsRoute
  '/t/$tenantId': typeof TTenantIdRouteRouteWithChildren
  '/t/$tenantId/': typeof TTenantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/tenants'
    | '/t/$tenantId'
    | '/t/$tenantId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/signin' | '/signup' | '/tenants' | '/t/$tenantId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/tenants'
    | '/t/$tenantId'
    | '/t/$tenantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TenantsRoute: typeof TenantsRoute
  TTenantIdRouteRoute: typeof TTenantIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenantId': {
      id: '/t/$tenantId'
      path: '/t/$tenantId'
      fullPath: '/t/$tenantId'
      preLoaderRoute: typeof TTenantIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenantId/': {
      id: '/t/$tenantId/'
      path: '/'
      fullPath: '/t/$tenantId/'
      preLoaderRoute: typeof TTenantIdIndexRouteImport
      parentRoute: typeof TTenantIdRouteRoute
    }
  }
}

interface TTenantIdRouteRouteChildren {
  TTenantIdIndexRoute: typeof TTenantIdIndexRoute
}

const TTenantIdRouteRouteChildren: TTenantIdRouteRouteChildren = {
  TTenantIdIndexRoute: TTenantIdIndexRoute,
}

const TTenantIdRouteRouteWithChildren = TTenantIdRouteRoute._addFileChildren(
  TTenantIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TenantsRoute: TenantsRoute,
  TTenantIdRouteRoute: TTenantIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
